#!/bin/sh

## Medibuntu
##  # deb http://packages.medibuntu.org/ intrepid free non-free
##  # deb-src http://packages.medibuntu.org/ intrepid free non-free
wget -O- http://packages.medibuntu.org/medibuntu-key.gpg | sudo apt-key add -

## Opera
##  # deb http://deb.opera.com/opera/ stable non-free
wget -O- http://deb.opera.com/archive.key | sudo apt-key add -

## OpenOffice 3.0
##  # see http://www.openoffice.cz/navody/instalace-openoffice-org-3-v-linuxu
##  # deb http://ppa.launchpad.net/openoffice-pkgs/ubuntu intrepid main
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com D2BB86E0EBD0F0A43D4DB3A760D11217247D1CFF

## Google
##  # deb http://dl.google.com/linux/deb/ stable non-free
wget -O- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

## Xbmc
##  # deb http://ppa.launchpad.net/team-xbmc-intrepid/ubuntu intrepid main
##  # deb-src http://ppa.launchpad.net/team-xbmc-intrepid/ubuntu intrepid main
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 9117FCCCBCA93A97D9B4115E43C0AFF0D7FAE680

## FreeNX
##  # deb http://ppa.launchpad.net/freenx-team/ubuntu intrepid main
##  # deb-src http://ppa.launchpad.net/freenx-team/ubuntu intrepid main
# sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com F3A662B57D580D3A2E98E5152A8E3034D018A4CE

## VirtualBox
##  # deb http://download.virtualbox.org/virtualbox/debian intrepid non-free
wget -O- http://download.virtualbox.org/virtualbox/debian/sun_vbox.asc | sudo apt-key add -

## KDE 4.2
##  # deb http://ppa.launchpad.net/kubuntu-experimental/ubuntu intrepid main
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com F3C48CB3011FA791D74ACAAC60487016493B3065

## KDE 4 - Amarok
##  # deb http://ppa.launchpad.net/kubuntu-members-kde4/ubuntu intrepid main
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 98F4AD08F5B1A7304029D4A99423A34CCA967634

## Kdenlive
##  # deb http://ppa.launchpad.net/baudm/ubuntu intrepid main
##  # deb-src http://ppa.launchpad.net/baudm/ubuntu intrepid main
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com F8DAF736A0F5EEE030AE0B9CB00E04A9D58062FB

## KDE Partition Manager
##  # see http://www.kde-apps.org/content/show.php/KDE+Partition+Manager?content=89595
##  # deb http://ppa.launchpad.net/vl-fidra/ubuntu intrepid main
##  # deb-src http://ppa.launchpad.net/vl-fidra/ubuntu intrepid main
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 733A4FC2F9E38CA0A5C15840658E9A05C80AD40A

## webKam
##  # see http://www.kde-apps.org/content/show.php/webKam?content=76902
##  # deb http://ppa.launchpad.net/alessandro-ghersi/ubuntu intrepid main
##  # deb-src http://ppa.launchpad.net/alessandro-ghersi/ubuntu intrepid main
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2CAD8FB991426969F54F99D747A309C3C8BABFBA
