#!/bin/sh

# http://sourceforge.net/project/showfiles.php?group_id=22866&package_id=16942
# http://www.jboss.org/jbossas/downloads/

VER="${1:-5.0.1.GA-jdk6}"
ARC="jboss-$VER.zip"
DIR="jboss-${VER%-jdk*}"
DLD="/var/cache/install"
DST="/usr/lib"


echo == Download $ARC from sourceforge.net to $DLD

[ -d "$DLD" ] || mkdir -p "$DLD" || exit 1

wget-sourceforge jboss "$DLD/$ARC" $2

[ ! -f "$DLD/$ARC" ] && echo !! Download failed. Check $DLD/$ARC.log for details. >&2 && exit 1


echo == Extract $DLD/$ARC to $DST/$DIR

unzip -qn "$DLD/$ARC" -d "$DST" "$DIR/*" || exit $?

if [ -d "$DST/$DIR" ]; then

    echo == Symlink $DST/jboss to $DST/jboss-${VER%-*}

    ln -s "$DST/$DIR" "$DST/jboss"

    fi
