#!/bin/sh

VER="${1:-2.2.1}"
ARC="jython_installer-$VER.jar"
DLD="/var/cache/install"
DST="/usr/lib/jython"
TMP="/var/cache/jython"


echo == Download $ARC from sourceforge.net to $DLD

[ -d "$DLD" ] || mkdir -p "$DLD" || exit 1

wget-sourceforge jython "$DLD/$ARC" $2

[ ! -f "$DLD/$ARC" ] && echo !! Download failed. Check $DLD/$ARC.log for details. >&2 && exit 1


echo == Install $DLD/$ARC to $DST

java -jar "$DLD/$ARC" -s -t standard -d "$DST" || exit $?


if [ -e "$DST/jython" ]; then

    echo == Symlink /usr/bin/jython to $DST/jython

    ln -s "$DST/jython" /usr/bin/jython


    echo == Symlink $DST/cachedir to $TMP

    [ -d "$TMP" ] || mkdir "$TMP"
    chmod 0755 "$TMP"
    ln -s "$TMP" "$DST/cachedir"

    fi
