#!/bin/sh

sudo aptitude install openssh-server

if [ -n "$1" -a "$1" != "22" ]; then
    sudo sed -i "s/^\( *Port\)\( \+=\? *\| *=\? +\|=\).*/\1\2$1/" /etc/ssh/sshd_config
    grep "^ *Port \+" /etc/ssh/sshd_config
    sudo invoke-rc.d ssh force-reload
    fi
