#!/bin/sh
rep=http://admin-scripts.googlecode.com/svn/trunk/linux/
dst=/usr/bin/

${1%%/*}
for f in "$@"; do 
   [ -z "$f" ]  && continue
   [ -z "${f##*/}" ]  && [ -d "$f" ]  && dst="$1"  ||  ( echo "Installing $dst$f"  && wget "$rep$f" -P "$dst"  && chmod +x "$dst$f" )
done
