#!/bin/sh

compiz_on () {
    #gnome-window-decorator &
    compiz --replace &
        #gconf
    [ -x avant-window-navigator ] && avant-window-navigator &
    }

compiz_off () {
    #killall gnome-window-decorator
    pkill -TERM avant-window-na
    metacity --replace
    }

compiz_status () {
    ps -C compiz.real > /dev/null
    return $?
    }

case "$1" in
    (on)
        compiz_status || compiz_on
        ;;
    (off)
        compiz_status && compiz_off
        ;;
    (switch)
        compiz_status && compiz_off || compiz_on
        ;;
    (status)
        compiz_status
        exit $?
        ;;
    (*)
        echo "Usage: ${0##*/} on|off|switch|status" 2>&1
        exit 2
        ;;
esac
